### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by JonasOlson** [absmall/ptmake#1]
Build instructions would be great. For example, there are a bunch of errors along the lines of ``/usr/bin/ld: ./libptmake.so: undefined reference to `gcry_md_open'``, that it isn't clear how to get rid of. Maybe it is a matter of library versions. I don't know.

Is this project alive and functioning, by the way? I was going to create one that did exactly the same thing, but then I discovered that this already exists.

**Comment by absmall** [comment]
It is not alive - I haven't looked at this for many years.

My views on building have evolved over the years. At the time I wrote this, I primarily used make, and it was a pain to get dependencies right, so much so that I often skipped it, and had incorrect dependencies. I started this project to address the problem. I abandoned it after a while because I found that the ptracing was slowing things down too much.

Now I primarily use [meson](https://mesonbuild.com) for building and sometimes [cmake](https://cmake.org) or [bazel](https://docs.bazel.build/versions/4.0.0/bazel-overview.html). I no longer see a reason to use make, as high level build tools are now easy enough and have both good enough built in dependency scanning for source code and good enough facilities to add your own dependency scanners, that I no longer see it as being worth the cost in build speed that ptrace causes to deal with dependency problems, when I really never run into dependency problems anymore with these tools.

That said, I thought at the time that this project was quite interesting, I will see if I can bring the code up to modern standards and add some instructions in the next few weeks.

**Comment by absmall** [comment]
Redid the build system and added instructions. Let me know if you want to collaborate on this. I'm not interested in reviving it on my own, but would work with someone else to revive it.

**Comment by JonasOlson** [comment]
> I found that the ptracing was slowing things down too much.

All right. I was hoping that only syscalls would be slower (maybe that is the case) and that build commands wouldn't primarily spend their time doing syscalls.

> Now I primarily use [meson](https://mesonbuild.com) for building and sometimes [cmake](https://cmake.org) or [bazel](https://docs.bazel.build/versions/4.0.0/bazel-overview.html). I no longer see a reason to use make, as high level build tools are now easy enough and have both good enough built in dependency scanning for source code and good enough facilities to add your own dependency scanners, that I no longer see it as being worth the cost in build speed that ptrace causes to deal with dependency problems, when I really never run into dependency problems anymore with these tools.

What attracts me to the method used by ptmake is its generality. I mean things like rendering an SVG file, which includes a link to some other image file, without knowing anything about the SVG format. Some dependencies might even be impossible to know until run time (of the build command).

By the way, the build instructions in https://github.com/absmall/ptmake/commit/ba2dcee0bebec406acd0eaa8b614c7289296e66b give me an error:
```
$ meson setup build

ERROR: Neither directory contains a build file meson.build.
```
Am I missing some file?

**Comment by absmall** [comment]
Yes, just the syscalls. But there are enough to make it significantly slower for me. Possibly a different usecase than mine would use fewer.

Sorry, I missed checking in a file. Fixed.
